version: '3.3'

services:
  
  client:
    build:
      context: ../../../
      dockerfile: client/Dockerfile
    ports:
       - "3000:3000"
    networks:
      - locatec

  
  server:
    build: 
      context: ../../../
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - locatec



  database:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=user

networks:
  locatec: